services:
  postgres:
    image: postgres:16-alpine
    container_name: tg-archive-bot-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YOUR_POSTGRES_PASSWORD_HERE
      POSTGRES_DB: tg_archive_bot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-tg_archive_bot}" ]
      interval: 5s
      timeout: 5s
      retries: 5
  tg-archive-bot:
    build:
      context: .
      dockerfile: Dockerfile
    # OR pull from registry
    # image: git.ewenlau.net/ewenlau/tg-archive-bot:latest
    # image: git.ewenlau.net/ewenlau/tg-archive-bot:dev
    container_name: tg-archive-bot
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      TG_BOT_DISCORD_TOKEN: YOUR_DISCORD_TOKEN_HERE
      TG_BOT_DISCORD_CLIENT_ID: YOUR_DISCORD_CLIENT_ID_HERE
      TG_BOT_DISCORD_CLIENT_SECRET: YOUR_DISCORD_CLIENT_SECRET_HERE
      TG_BOT_DISCORD_REDIRECT_URI: http://localhost:3000/login/discord/callback
      TG_BOT_DATABASE_URL: postgres://postgres:YOUR_POSTGRES_PASSWORD_HERE@postgres:5432/tg_archive_bot
      TG_BOT_LOG: info
      TG_BOT_WEB_ADDRESS: 0.0.0.0:3000

volumes:
  postgres_data:
    driver: local
